### ISSUE TITLE
Day 4 only shows part 2's answer.

### ISSUE THREAD

**Issue by OurSickStory** [xPaw/adventofcode-solutions#1]
Just a heads up, as it only displays it with 6 0's as part one displays 5 0's.
(for you live website part)

**Comment by xPaw** [comment]
This was intended as the description says "start with at least five zeroes". I haven't actually confirmed if the site accepts this as an answer, but I don't see why it shouldn't.

**Comment by wizardfrag** [comment]
It needs to be the lowest number though. This might not be the case with 6 zeroes

**Comment by xPaw** [comment]
Oh, that's a good point!
